name: CI/CD Pipeline for Loan Amortization System

# Triggers: Run on push and pull request to specific branches
on:
  push:
    branches:
      - main
      - development
      - Feature
      - flutter
      - bugfix
      - hotfix
  pull_request:
    branches:
      - main
      - development
      - Feature
      - flutter
      - bugfix
      - hotfix

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14, 16]  # Specify relevant Node.js versions for testing

    steps:
      # Step 1: Check out the repository code
      - name: Check out code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      # Step 3: Install dependencies for backend and frontend
      - name: Install dependencies
        run: |
          cd backend && npm install
          cd ../frontend && npm install

      # Step 4: Run tests for backend
      - name: Run backend tests
        working-directory: ./backend
        run: npm test

      # Step 5: Run tests for frontend
      - name: Run frontend tests
        working-directory: ./frontend
        run: npm test
