name: CI/CD Pipeline for Loan Amortization System

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  backend:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}
          MYSQL_DATABASE: test_db
          MYSQL_USER: ${{ secrets.DB_USER }}
          MYSQL_PASSWORD: ${{ secrets.DB_PASSWORD }}
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        ports:
          - 3306:3306

    steps:
      # Step 1: Check out the code
      - name: Check out code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js for backend
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Step 3: Install backend dependencies
      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install

      # Step 4: Run backend tests
      - name: Run backend tests
        working-directory: ./backend
        env:
          DB_HOST: 127.0.0.1
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: test_db
        run: npm test

      # Step 5: Lint backend code
      - name: Lint backend code
        working-directory: ./backend
        run: npm run lint

  frontend:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Check out code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js for frontend
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Step 3: Install frontend dependencies
      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      # Step 4: Build frontend
      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

      # Step 5: Run frontend tests
      - name: Run frontend tests
        working-directory: ./frontend
        run: npm test

      # Step 6: Lint frontend code
      - name: Lint frontend code
        working-directory: ./frontend
        run: npm run lint

