name: CI/CD Pipeline for Loan Amortization System

on:
  push:
    branches:
      - main
      - development
      - Feature
      - bugfix
      - hotfix
      - flutter
  pull_request:
    branches:
      - main
      - development
      - Feature
      - bugfix
      - hotfix
      - flutter

jobs:
  # Backend job for Node.js/Express and MySQL
  backend:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}
          MYSQL_DATABASE: test_db
          MYSQL_USER: ${{ secrets.DB_USER }}
          MYSQL_PASSWORD: ${{ secrets.DB_PASSWORD }}
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        ports:
          - 3306:3306

    steps:
      - name: Check out code
<<<<<<< HEAD
        uses: actions/checkout@v3  # Updated version

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Updated version
=======
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
>>>>>>> c8177e55e431889de92079709b9c763dc8ca6ff1
        with:
          node-version: '16'

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install

      - name: Run backend tests
        working-directory: ./backend
        env:
          DB_HOST: 127.0.0.1
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: test_db
        run: npm test

      - name: Build backend
        working-directory: ./backend
        run: npm run build

  # Frontend job for Vite and Tailwind CSS
  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
<<<<<<< HEAD
        uses: actions/checkout@v3  # Updated version

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Updated version
=======
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
>>>>>>> c8177e55e431889de92079709b9c763dc8ca6ff1
        with:
          node-version: '16'

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      - name: Run frontend tests
        working-directory: ./frontend
        run: npm test

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

<<<<<<< HEAD
  # Flutter job for the flutter branch
  flutter:
    if: github.ref == 'refs/heads/flutter'  # Run only on flutter branch
=======
  # Flutter job only for the flutter branch
  flutter:
    if: github.ref == 'refs/heads/flutter'
>>>>>>> c8177e55e431889de92079709b9c763dc8ca6ff1
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
<<<<<<< HEAD
        uses: actions/checkout@v3  # Updated version
=======
        uses: actions/checkout@v2
>>>>>>> c8177e55e431889de92079709b9c763dc8ca6ff1

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
<<<<<<< HEAD
          flutter-version: '2.5.3'  # Ensure this version is supported in the workflow
=======
          flutter-version: '2.5.3'
>>>>>>> c8177e55e431889de92079709b9c763dc8ca6ff1

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test

      - name: Build Flutter app
        run: flutter build apk
